package pages;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DataTable2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dataTable2() {
    driver.get("https://editor.datatables.net/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".buttons-create")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".buttons-create"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("DTE_Field_first_name")).sendKeys("Ali");
    driver.findElement(By.id("DTE_Field_last_name")).sendKeys("Can");
    driver.findElement(By.id("DTE_Field_position")).sendKeys("Customer Servise");
    driver.findElement(By.id("DTE_Field_office")).click();
    driver.findElement(By.id("DTE_Field_office")).sendKeys("Newyork");
    driver.findElement(By.id("DTE_Field_extn")).click();
    driver.findElement(By.id("DTE_Field_extn")).sendKeys("123");
    driver.findElement(By.id("DTE_Field_start_date")).click();
    driver.findElement(By.cssSelector(".dt-datetime-calendar tr:nth-child(2) > .selectable:nth-child(2) span")).click();
    driver.findElement(By.id("DTE_Field_start_date")).sendKeys("2024-10-08");
    driver.findElement(By.id("DTE_Field_salary")).click();
    driver.findElement(By.id("DTE_Field_salary")).sendKeys("25000");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.close();
  }
}
